config/routes.rb
Rails.application.routes.draw do
  get 'pages/thankyou'
  get 'pages/baa'
  resources :baas

  resources :templates

  resources :documents
  resources :charges
  devise_for :users, controllers: { registrations: "registrations" }

  root 'documents#index'
  post 'blitline_callbacks' => 'blitline_callbacks#create'

end

app/models/baa.rb
class Baa < ActiveRecord::Base
end

app/controllers/baas_controller.rb
class BaasController < ApplicationController
  before_action :set_baa, only: [:show, :edit, :update, :destroy]

  # GET /baas
  # GET /baas.json
  def index
    @baas = Baa.all
  end

  # GET /baas/1
  # GET /baas/1.json
  def show
  end

  # GET /baas/new
  def new
    @baa = Baa.new
  end

  # GET /baas/1/edit
  def edit
  end

  # POST /baas
  # POST /baas.json
  def create
    @baa = Baa.new(baa_params)

    respond_to do |format|
      if @baa.save
        format.html { redirect_to @baa, notice: 'Baa was successfully created.' }
        format.json { render :show, status: :created, location: @baa }
      else
        format.html { render :new }
        format.json { render json: @baa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baas/1
  # PATCH/PUT /baas/1.json
  def update
    respond_to do |format|
      if @baa.update(baa_params)
        format.html { redirect_to @baa, notice: 'Baa was successfully updated.' }
        format.json { render :show, status: :ok, location: @baa }
      else
        format.html { render :edit }
        format.json { render json: @baa.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # DELETE /baas/1
  # DELETE /baas/1.json
  def destroy
    @baa.destroy
    respond_to do |format|
      format.html { redirect_to baas_url, notice: 'Baa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baa
      @baa = Baa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baa_params
      params.require(:baa).permit(:signature, :user_id)
    end
end

app/helpers/baas_helper.rb
module BaasHelper
end

app/views/baas/_form.html.erb
<%= form_for(@baa) do |f| %>
  <% if @baa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@baa.errors.count, "error") %> prohibited this baa from being saved:</h2>

      <ul>
      <% @baa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :signature %><br>
    <%= f.text_field :signature %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baas/edit.html.erb
<h1>Editing Baa</h1>

<%= render 'form' %>

<%= link_to 'Show', @baa %> |
<%= link_to 'Back', baas_path %>

app/views/baas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Baas</h1>

<table>
  <thead>
    <tr>
      <th>Signature</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baas.each do |baa| %>
      <tr>
        <td><%= baa.signature %></td>
        <td><%= baa.user_id %></td>
        <td><%= link_to 'Show', baa %></td>
        <td><%= link_to 'Edit', edit_baa_path(baa) %></td>
        <td><%= link_to 'Destroy', baa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baa', new_baa_path %>

app/views/baas/new.html.erb
<h1>New Baa</h1>

<%= render 'form' %>

<%= link_to 'Back', baas_path %>

app/views/baas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Signature:</strong>
  <%= current_user.signature %>
</p>

<p>


<%= link_to 'Edit', edit_baa_path(@baa) %> |
<%= link_to 'Back', baas_path %>