config/routes.rb
Rails.application.routes.draw do
  get 'pages/thankyou'
  get 'pages/baa'
  resources :baas

  resources :templates

  resources :documents
  resources :charges
  devise_for :users, controllers: { registrations: "registrations" }

  root 'documents#index'
  post 'blitline_callbacks' => 'blitline_callbacks#create'

end

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id='template_edit'>
<%= image_tag @template.processed_attachement_url, width: '1110'%>

</div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-success btn-lg text-center navbutton signbutton'%>
  </div>

<% end %>

app/views/templates/_sidebar.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
<%=link_to (image_tag("logo.png", width: '200', height: '75', :class => "sidebar-img")), root_path %>
                    </a>
                </li>
                <br>
                <li class="textwhite"> Hello there, <%= current_user.name %>! </li>                
                <li><%= link_to (image_tag("home.png", width: '15', height: '15')) + "  My Dashboard", root_path %>
                </li>
                <li><%= link_to (image_tag("edit.png", width: '15', height: '15')) + " My Templates", templates_path %></li>
                <li><%= link_to (image_tag("profile.png", width: '15', height: '15')) + " Edit my Profile", edit_user_registration_path %></li>
                                <li><%= link_to (image_tag("help.png", width: '15', height: '15')) + "  Help Documentation", 'http://esignhealth.com/help', :target => '_blank' %></li>

                <li>
                    <%= link_to (image_tag("out.png", width: '15', height: '15')) + " Exit", destroy_user_session_path,  :method=>'delete' %>
                </li>                

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12"><p id="notice"><%= notice %></p>

app/views/templates/edit.html.erb
<%= render 'form' %>

app/views/templates/index.html.erb
<%= render 'sidebar' %>

<h1>Your Templates</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th> Template Name </th>
      <th></th>
      <th> Signature Position</th>
      <th colspan="3"></th>
      
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr class="<%= template.processed_attachement_url ? 'success' : 'danger' %>">
        <td><%= template.name %></td>
        <% unless template.processed_attachement_url.blank? %>
        <td><%= link_to 'View', template %></td>
        <td>
          <% if template.signature_position.blank? %><%= link_to 'Set Signature Position', edit_template_path(template) %> <% else %> <%= image_tag('checkmark.png', :class => 'center')  %>  Already Set -- <%= link_to 'Change Signature Position', edit_template_path(template) %></td><% end %>
        <td><%= link_to 'Delete Template', template, method: :delete, data: { confirm: "Are you sure?  Any documents you've created using this template will no longer be available" } %></td>
<% else %>
        <td> </td>
        <td> </td>
<td><%= link_to 'Delete Template', template, method: :delete, data: { confirm: "Are you sure?  Any documents you've created using this template will no longer be available" } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Create a new Template', new_template_path, :class =>"btn btn-success", :method => :get  %>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="/javascripts/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

app/views/templates/new.html.erb
<%= render 'sidebar' %>

<h1>Create a New Template</h1>

<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>
<div class="fields">
  Give your template a name
  <%= f.text_field :name %>
</div>
<br>
<div class="fields">
  Upload your template  <%= f.file_field :attachment1 %>
  <b>eSignHealth currently accepts PDF Files only!</b>
</div>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<%= stylesheet_link_tag 'documents.scss', :media => "all" %>
<%= image_tag @template.processed_attachement_url, width: '1110'%>