config/routes.rb
Rails.application.routes.draw do
  get 'pages/thankyou'
  get 'pages/baa'
  resources :baas

  resources :templates

  resources :documents
  resources :charges
  devise_for :users, controllers: { registrations: "registrations" }

  root 'documents#index'
  post 'blitline_callbacks' => 'blitline_callbacks#create'

end

app/models/document.rb
class Document < ActiveRecord::Base

belongs_to :user
has_many :dynamic_textfields
accepts_nested_attributes_for :dynamic_textfields
belongs_to :template

	before_create :add_token
		private
		def add_token
		  begin
		    self.authentication_token = SecureRandom.hex[0,10].upcase
		  end while self.class.exists?(authentication_token: authentication_token)
		end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!, except: [:edit, :update]
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = current_user.documents.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)

    # if current_user.documents.count <= 1000
    #   render "modal"
    # end

  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render    :pdf => "file",
                  :template => 'documents/show.html.erb',
                  :javascript_delay => '500',
                  :page_size =>        'Letter',
               margin:  {   top:               5,                     # default 10 (mm)
                            bottom:            5,
                            left:              0,
                            right:             0 }                  
       end        
     end  
  end

  # GET /documents/new
  def new
      if current_user.documents.count >= 10 && !current_user.subscribed
        redirect_to new_charge_path
      else
        @document = Document.new
        @document.user_id = current_user.id
        @available_templates = @current_user.templates.map{|tmplt| [tmplt.name, tmplt.id]}

      end
  end
  # GET /documents/1/edit
  def edit
    # Remove and edit this so that it validates against the token and id
    #if @document.signature.present?
    #redirect_to pages_error_path
  #else
    @document = Document.find_by(authentication_token: params[:authentication_token], id: params[:id])
    #end
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = @document = Document.new(document_params)
    @document.user_id = current_user.id
    #@document.template_name = @template.name --- Save template name
    respond_to do |format|
      if @document.save
        DocumentMailer.email(@document).deliver_later
        format.html { redirect_to documents_path, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
        #DocumentMailer.reminder(@document).deliver_later <-- Decided this wasn't a critical function
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        DocumentMailer.update(@document).deliver_later
        # TODO: replace root_path with pages_thankyou_path
        format.html { redirect_to "http://esignhealth.com", notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:template_id, :recipient, :user_id, :signature, :dynamic_textfields_attributes => [:text, :left, :top])
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document, html: { multipart: true}) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<script src="\assets\json2.min.js"></script>
<link href="\assets\jquery.signaturepad.css" rel="stylesheet">
<div id="textfields" style="cursor:text">
<%= image_tag @document.template.processed_attachement_url, width: '1110'%>
<!--Signature Modal -->
</div>

<div class="modal fade sigmodal" id="signatureModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign below to complete</h4>
      </div>
      <div class="modal-body">
        <form method="post" action="" class="sigPad">

    <div class="sigPad">
    <div class="sig sigWrappersignup">
       <canvas class="signuppad" width="498" height="73" style="cursor:crosshair" ></canvas>
      <%= f.hidden_field :signature, class: "output" %>
      </div>
    </div>
  </div>  
</div>
<div class="modal-footer">
   <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-primary" name="commit" value="Sign and Complete" />
      </div>
    </div>
  </div>
</div>

<!--
Instructions Modal
<div class="modal fade in" id="signatureModal" tabindex="-1"  aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign below to complete</h4>
      </div>
      <div class="modal-body">
        
        XX

 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="signatureModal">Close</button>
        </div>
    </div>
  </div>
</div>
-->
</div> <!-- image div -->

<!--<div class="center">
  <footer class="navbar navbar-default nav-float">-->
    <button class="btn btn-success btn-lg text-center navbutton signbutton" type="button" data-toggle="modal" data-target="#signatureModal">Complete and Sign</button>
<!--  </footer>
</div>-->

<!-- instructions modal -->
<script type="text/javascript">
    $(window).load(function(){
        $('#instructionsmodal').modal('show');
    });
</script>

<!-- Modal -->
<div class="modal fade" id="instructionsmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="center"><%= image_tag("graylogo.jpg", width: '200', height: '75') %></div>      </div>
      <div class="modal-body">
        <h4>This is going to be a breeze...</h4>
        <strong>Completing this document is as simple as clicking anywhere on the document.</strong><br>  If you're using a mobile device with a touch screen, you might have to hold your touch for a second or longer.  An input box will show up where you clicked, then just type away.  Take as many inputs as you need to complete the document.
</br><br>
        Once you've filled out all the important parts, <strong>click the green "Complete and Sign" button in the lower right corner.</strong> Simply sign with your mouse or touchscreen device, then carry on with your busy day!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">Ok, got it!</button>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/documents/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/documents/_sidebar.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
<%=link_to (image_tag("logo.png", width: '200', height: '75', :class => "sidebar-img")), root_path %>
                    </a>
                </li>
                <br>
                <li class="textwhite"> Hello there, <%= current_user.name %>! </li>                
                <li><%= link_to (image_tag("home.png", width: '15', height: '15')) + "  My Dashboard", root_path %>
                </li>
                <li><%= link_to (image_tag("edit.png", width: '15', height: '15')) + "  My Templates", templates_path %></li>
                <li><%= link_to (image_tag("profile.png", width: '15', height: '15')) + "  Edit my Profile", edit_user_registration_path %></li>
                <li>
                <li><%= link_to (image_tag("help.png", width: '15', height: '15')) + "  Help Documentation", 'http://esignhealth.com/help', :target => '_blank' %></li>
                <!-- Button trigger modal
                <a data-toggle="modal" data-target="#instmodal" ><img width="15" height="15" src="assets/help.png">
                  Help
                </a></li> -->
                <li>
                    <%= link_to (image_tag("out.png", width: '15', height: '15')) + " Exit", destroy_user_session_path,  :method=>'delete' %>
                </li>

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12"><p id="notice"><%= notice %></p>

app/views/documents/edit.html.erb
<%= render 'form' %>

app/views/documents/index.html.erb
<%= render 'sidebar' %>

<h1>Your Documents</h1>

<table>
    <table class="table table-hover">
  <thead>
    <tr>
      <th>Date Created</th>
      <th>Sent to</th>
      <th>Signed</th>

      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |document| %>
      <tr class="<%= document.signature ? 'success' : 'danger' %>">
        <td><%= document.created_at.strftime("%b %d %Y at %I:%M %p") %> UTC</td>
        <td><%= document.recipient %></td>

        <td><%= image_tag('checkmark.png') if document.signature? %></td>
        <td><%= link_to 'Open PDF',  document_path(document, :format => "pdf")%> </td>
        <td><%= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>
<div class="center"><%= will_paginate @documents %></div>
<br>

<%= button_to 'Send a New Document', new_document_path, :class =>"btn btn-success", :method => :get  %>
 
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="/javascripts/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>




<!-- Modal -->
<div class="modal fade" id="instmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Help</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

</body>

</html>

app/views/documents/new.html.erb
<%= render 'sidebar' %>
<h1>Send a new document</h1>
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label "Template " %><br>
    <%= f.select :template_id, @available_templates,
 {prompt: 'Select a template'}, {required: true} %>
  </div>
    <div class="field">
    <%= f.label "Recipient" %><br>
    <%= f.text_field :recipient %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', documents_path %>